I'm sorry, but an uncaught exception occurred.

While loading <'Image' 'mods/delaemmod/image/medpunkt.jpg'>:
  File "/storage/emulated/0/Android/data/su.sovietgames.everlasting_summer/files/PacanSummer/mods/delaemmod.rpy", line 3016, in script
    scene bg ext_aidpost_night with dissolve
IOError: Couldn't find file 'mods/delaemmod/image/medpunkt.jpg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/storage/emulated/0/Android/data/su.sovietgames.everlasting_summer/files/PacanSummer/mods/delaemmod.rpy", line 3016, in script
    scene bg ext_aidpost_night with dissolve
  File "D:\renpy-6.99.5\renpy\ast.py", line 1250, in execute
  File "D:\renpy-6.99.5\renpy\exports.py", line 1252, in with_statement
  File "D:\renpy-6.99.5\renpy\display\core.py", line 1865, in do_with
  File "D:\renpy-6.99.5\renpy\display\core.py", line 2285, in interact
  File "D:\renpy-6.99.5\renpy\display\core.py", line 2622, in interact_core
  File "D:\renpy-6.99.5\renpy\display\core.py", line 1725, in draw_screen
  File "renpy/display/render.pyx", line 379, in renpy.display.render.render_screen (gen/renpy.display.render.c:5907)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen/renpy.display.render.c:2683)
  File "D:\renpy-6.99.5\renpy\display\layout.py", line 650, in render
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen/renpy.display.render.c:3066)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen/renpy.display.render.c:2683)
  File "D:\renpy-6.99.5\renpy\display\transition.py", line 361, in render
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen/renpy.display.render.c:3066)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen/renpy.display.render.c:2683)
  File "D:\renpy-6.99.5\renpy\display\layout.py", line 650, in render
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen/renpy.display.render.c:3066)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen/renpy.display.render.c:2683)
  File "D:\renpy-6.99.5\renpy\display\layout.py", line 650, in render
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen/renpy.display.render.c:3066)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen/renpy.display.render.c:2683)
  File "renpy/display/accelerator.pyx", line 104, in renpy.display.accelerator.transform_render (gen/renpy.display.accelerator.c:1888)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen/renpy.display.render.c:2683)
  File "D:\renpy-6.99.5\renpy\display\image.py", line 218, in render
  File "D:\renpy-6.99.5\renpy\display\image.py", line 90, in wrap_render
  File "renpy/display/render.pyx", line 103, in renpy.display.render.render (gen/renpy.display.render.c:3066)
  File "renpy/display/render.pyx", line 185, in renpy.display.render.render (gen/renpy.display.render.c:2683)
  File "D:\renpy-6.99.5\renpy\display\im.py", line 478, in render
  File "D:\renpy-6.99.5\renpy\display\im.py", line 200, in get
  File "D:\renpy-6.99.5\renpy\display\im.py", line 529, in load
  File "D:\renpy-6.99.5\renpy\loader.py", line 512, in load
IOError: Couldn't find file 'mods/delaemmod/image/medpunkt.jpg'.

